#======================================================================================/
#**    Author: Jack Dempsey                                             	           /
#**    Date:   11/21/2018                                                              /
#**    Description: MakeFile for SmithWatermanRaspi                                /
#**    After running this makefile the user will be able to run the two
#======================================================================================/
C++  = g++
FLAGS = -std=c++11
C++VERSION 	= ${C++} -dumpversion

RUN:	SWAlgo.o SWEncode.c Complete.o


SWAlgo.o:
	@printf "\n============Compiling SWAlgo============\n"
	

SWEncode.o:
	@printf "\n============Compiling SWEncode==========\n"
	
	
Complete.o:
	@printf "\n========COMPILATION COMPLETE=============\n"
	
clean: 
@rm -f *.o SWAlgo.exe SWEncode.exe 
